# Pengaturan Server
server.port=8080
spring.application.name=ludo-elite-backend

# Pengaturan Database H2 (Kunci URL, Username, dan Password Kosong)
spring.datasource.url=jdbc:h2:mem:ludodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pengaturan JPA / Hibernate (Otomatis buat tabel)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Aktifkan Akses Browser H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true